---
name: Build ASDX image

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build ${{ matrix.recipe }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - asdx.yml
          - asdx-arm64.yml

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build ASDX image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          registry: ghcr.io
          registry_namespace: ${{ github.repository_owner }}
          registry_token: ${{ github.token }}
          registry_username: ${{ github.actor }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          pr_event_number: ${{ github.event.number }}
          push: ${{ github.event_name != 'pull_request' }}
